apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-music-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-music-backend
  template:
    metadata:
      labels:
        app: ai-music-backend
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4" # example for GPU nodes
      containers:
        - name: backend
          image: ghcr.io/candy11212/den-ai-music-starter/backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: ai-music-secrets
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              cpu: "1000m"
              memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-music-backend
spec:
  selector:
    app: ai-music-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
